version: "3.8"

services:
  # Database Services
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: trading_platform
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trading_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - trading_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trading_network

  influxdb:
    image: influxdb:2.7-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: trading-platform
      DOCKER_INFLUXDB_INIT_BUCKET: market-data
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - trading_network

  # Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: trading_user
      RABBITMQ_DEFAULT_PASS: trading_password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - trading_network

  # Monitoring Services
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
    networks:
      - trading_network

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - trading_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - trading_network

  # Core Services (Development)
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://trading_user:trading_password@postgres:5432/trading_platform
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://trading_user:trading_password@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - trading_network
    volumes:
      - ./services/api-gateway:/app
      - ./shared:/app/shared

  trading-engine:
    build:
      context: .
      dockerfile: services/trading-engine/Dockerfile
    environment:
      - DATABASE_URL=postgresql://trading_user:trading_password@postgres:5432/trading_platform
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://trading_user:trading_password@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - trading_network
    volumes:
      - ./services/trading-engine:/app
      - ./shared:/app/shared

  market-data:
    build:
      context: .
      dockerfile: services/market-data/Dockerfile
    environment:
      - DATABASE_URL=postgresql://trading_user:trading_password@postgres:5432/trading_platform
      - REDIS_URL=redis://redis:6379
      - INFLUXDB_URL=http://influxdb:8086
      - RABBITMQ_URL=amqp://trading_user:trading_password@rabbitmq:5672
    depends_on:
      - postgres
      - redis
      - influxdb
      - rabbitmq
    networks:
      - trading_network
    volumes:
      - ./services/market-data:/app
      - ./shared:/app/shared

  strategy-marketplace:
    build:
      context: .
      dockerfile: services/strategy-marketplace/Dockerfile
    ports:
      - "8007:8007"
    environment:
      - STRATEGY_MARKETPLACE_DATABASE_URL=postgresql://trading_user:trading_password@postgres:5432/trading_platform
      - JWT_SECRET_KEY=your-secret-key-here
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://trading_user:trading_password@rabbitmq:5672
      - AUTH_SERVICE_URL=http://api-gateway:8000
      - TRADING_ENGINE_URL=http://trading-engine:8002
      - STRATEGY_ENGINE_URL=http://strategy-engine:8003
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - trading_network
    volumes:
      - ./services/strategy-marketplace:/app
      - ./shared:/app/shared

volumes:
  postgres_data:
  redis_data:
  influxdb_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:

networks:
  trading_network:
    driver: bridge
